apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/docker/docker-compose.yml -o /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/k8s-manifests
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frappe
  name: frappe
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frappe
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/docker/docker-compose.yml -o /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/k8s-manifests
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: frappe
    spec:
      containers:
        - args:
            - bash
            - /workspace/init.sh
          env:
            - name: SHELL
              value: /bin/bash
          image: frappe/bench:latest
          name: frappe
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: frappe-cm0
          workingDir: /home/frappe
      restartPolicy: Always
      volumes:
        - configMap:
            name: frappe-cm0
          name: frappe-cm0
