apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/docker/docker-compose.yml -o /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/k8s-manifests
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/docker/docker-compose.yml -o /Users/adinortey/Desktop/Projects/Odeen/frappe-lms/k8s-manifests
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake
            - --skip-innodb-read-only-compressed
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          image: mariadb:10.6
          name: mariadb
          volumeMounts:
      - name: mariadb-pv
        mountPath: /var/lib/mysql
            - mountPath: /var/lib/mysql
              name: mariadb-data
      restartPolicy: Always
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
